In [1]:
import numpy as np

Ejercicio 5

In [3]:
# Numero de intentos
n = 5

for i in range(n):
    A = np.random.randint(0, 5, size=(5, 5))
    B = np.random.randint(0, 5, size=(5, 5))
    det = np.linalg.det(A + B) - np.linalg.det(A) - np.linalg.det(B)
    print(f'det (A+B) - det(A) - det(B) = {det}')


det (A+B) - det(A) - det(B) = -272.99999999999994
det (A+B) - det(A) - det(B) = -665.0
det (A+B) - det(A) - det(B) = 104.00000000000014
det (A+B) - det(A) - det(B) = 752.0000000000005
det (A+B) - det(A) - det(B) = -45.999999999999964


Ejercicio 6

In [9]:
# Numero de intentos
n = 5

for i in range(n):
    A = np.random.randint(0, 5, size=(5, 5))
    B = np.random.randint(0, 5, size=(5, 5))
    print(f'det (AB) = {round(np.linalg.det(A @ B))}, det(A)det(B) = {round((np.linalg.det(A) * np.linalg.det(B)))}')

det (AB) = 14256, det(A)det(B) = 14256
det (AB) = 17280, det(A)det(B) = 17280
det (AB) = -480, det(A)det(B) = -480
det (AB) = 1200, det(A)det(B) = 1200
det (AB) = -8008, det(A)det(B) = -8008


Ejercicio 12

In [70]:
def cramer(A, b):
    n = b.shape[0]
    x = np.zeros(b.shape)
    for i in range(n):
        Ai_b = A.copy()
        Ai_b[:, i] = b.flatten()
        x[i, 0] = np.linalg.det(Ai_b) / np.linalg.det(A)

    return x


# Numero de intentos
n = 1

for i in range(n):
    A = np.random.randint(0, 5, size=(4, 4))
    b = np.random.randint(0, 5, size=(4, 1))
    
    try:
        x_1 = np.linalg.solve(A, b)
        x_2 = cramer(A, b)
        for j in range(x_1.shape[0]):
            print("Xi = {0:.2f} = {1:.2f}".format(x_1[i,0], x_2[i,0]))

    except:
        print("Matriz singular")

Xi = 2.33 = 2.33
Xi = 2.33 = 2.33
Xi = 2.33 = 2.33
Xi = 2.33 = 2.33


**Ejercicio 10**

- $x_{k+1} = A^kx_0$

Queremos ver si para una matriz $A$ con valores aleatorios, el metodo de la potencia converge a un autovector de $A$. Para ello, creamos una secuencia con $k = 0, 1, ...$ y comparamos el autovector y autovalor al que devuelve la funcion `np.linalg.eig`

In [32]:
A = np.random.randint(0, 10, size=(4, 4))
x_0 = np.array([1, 0, 1, 0]).reshape(-1, 1)

In [33]:
# Autovector y autovalor de np.linalg.eig
values, vectors = np.linalg.eig(A)
v1 = vectors[:, 0]
valor = values[0].real

print('k\tValorEstimado\tVectorEstimado')

for k in range(15):
    # Calculamos X_k+1 = A^k * x_0
    x_k1 = np.linalg.matrix_power(A, k) @ x_0

    # Normalizamos el vector x_k1
    x_k1_norm = x_k1 / np.linalg.norm(x_k1)
    # Extraemos el autovalor de x_k1_norm
    autovalor_k = x_k1_norm.T @ A @ x_k1_norm

    # Comparamos resultados
    print(f'{k}\t{autovalor_k[0][0]:.2f}\t\t{x_k1_norm.flatten().round(2)}')

print(f'\n\tValor np\tVector np')
print(f'\t{valor:.2f}\t\t{v1.round(2)}')


k	ValorEstimado	VectorEstimado
0	8.50		[0.71 0.   0.71 0.  ]
1	12.32		[0.65 0.46 0.46 0.39]
2	12.55		[0.66 0.31 0.39 0.56]
3	12.50		[0.56 0.3  0.41 0.65]
4	12.34		[0.53 0.28 0.37 0.71]
5	12.23		[0.5  0.26 0.36 0.75]
6	12.14		[0.48 0.25 0.35 0.77]
7	12.07		[0.46 0.24 0.34 0.78]
8	12.02		[0.45 0.24 0.33 0.79]
9	11.99		[0.45 0.23 0.33 0.8 ]
10	11.96		[0.44 0.23 0.33 0.8 ]
11	11.94		[0.44 0.23 0.32 0.81]
12	11.93		[0.43 0.23 0.32 0.81]
13	11.92		[0.43 0.23 0.32 0.81]
14	11.91		[0.43 0.23 0.32 0.81]

	Valor np	Vector np
	11.89		[0.43+0.j 0.22+0.j 0.32+0.j 0.82+0.j]


Usamos el metodo de la potencia de manera diferente. Calculamos la secuencia con la siguiente formula:
- $x_{k+1} = 1/u_{k}(Ax_k)$ donde $u_{k} =$ entrada con mayor valor absoluto de $Ax_k$

In [36]:
def sucecion_potencias(A, x_k) -> tuple:
    Ax = A @ x_k
    u_k = max(abs(Ax))
    x_k1 = Ax / u_k

    return x_k1, u_k

x_k = x_0
for k in range(15):
    x_k, u_k = sucecion_potencias(A, x_k)
    print((x_k / np.linalg.norm(x_k)).flatten().round(2), u_k)

[0.65 0.46 0.46 0.39] [10]
[0.66 0.31 0.39 0.56] [12.7]
[0.56 0.3  0.41 0.65] [12.5984252]
[0.53 0.28 0.37 0.71] [13.68125]
[0.5  0.26 0.36 0.75] [12.93823664]
[0.48 0.25 0.35 0.77] [12.60608789]
[0.46 0.24 0.34 0.78] [12.36898768]
[0.45 0.24 0.33 0.79] [12.22357304]
[0.45 0.23 0.33 0.8 ] [12.12374046]
[0.44 0.23 0.33 0.8 ] [12.05592384]
[0.44 0.23 0.32 0.81] [12.00877134]
[0.43 0.23 0.32 0.81] [11.97574371]
[0.43 0.23 0.32 0.81] [11.95245319]
[0.43 0.23 0.32 0.81] [11.93594681]
[0.43 0.23 0.32 0.81] [11.92421224]


**Ejercicio 11**

Comprobamos que tienen los mismos autovalores pero no los mismos autovectores

In [30]:
A = np.random.randint(-10, 10, (4, 4))

values_A, vectors_A = np.linalg.eig(A)
values_At, vectors_At = np.linalg.eig(A.T)

for i in range(4):
    print(values_A.flatten().round(2).real[i], '\t', values_At.flatten().round(2).real[i])

-15.1 	 -15.1
-3.53 	 -3.53
6.31 	 6.31
6.31 	 6.31


In [31]:
for i in range(4):
    print(vectors_A.real[:, i].round(2), '\t', vectors_At.real[:, i].round(2))

[-0.61 -0.46  0.28 -0.57] 	 [ 0.31  0.47 -0.15  0.81]
[-0.94  0.05  0.02  0.33] 	 [ 0.64 -0.2   0.73 -0.16]
[ 0.56  0.18 -0.54 -0.42] 	 [ 0.03  0.39  0.67 -0.02]
[ 0.56  0.18 -0.54 -0.42] 	 [ 0.03  0.39  0.67 -0.02]


Repetimos el experimento con matriz de 5x5

In [42]:
A = np.random.randint(-10, 10, (5, 5))

values_A, vectors_A = np.linalg.eig(A)
values_At, vectors_At = np.linalg.eig(A.T)

for i in range(5):
    print(values_A.flatten().round(2).real[i], '\t', values_At.flatten().round(2).real[i])

4.36 	 4.36
4.36 	 4.36
-13.22 	 -13.22
-6.25 	 -6.25
-6.25 	 -6.25
