In [2]:
import numpy as np

In [3]:
# Ejercicio 10

M = np.array([
    [1, 0, -1, 0],
    [0, 1, 0, 0],
    [-1, 0, 1, 0],
    [0, 0, 0, 1], 
])

patrones = []

def patron(vector, i=0):
    if i == 4:
        if (vector.T @ M @ vector == 0).all():
            global patrones
            patrones.append(vector)
    else:
        vector_0 = vector.copy()
        vector_0[i] = 0

        vector_1 = vector.copy()
        vector_1[i] = 1
        patron(vector_0, i+1)
        patron(vector_1, i+1)


patron(np.array([0, 0, 0, 0]))
patrones

[array([0, 0, 0, 0]), array([1, 0, 1, 0])]

In [16]:
patron_d = np.array([1, 0, 1, 0]).reshape(-1, 1)
patron_d.T @ M @ patron_d

array([[0]])

El patrón que detecta M es P = 
$\left[\begin{array}{ccc}
1 & 1\\
0 & 0
\end{array}\right]$

In [7]:
# Ejercicio 11
M = np.array([
    [1, 0, 0, -1],
    [0, 1, 0, -1],
    [0, 0, 1, 0],
    [-1, -1, 0, 2], 
])

patron_2 = np.array([1, 1, 0, 1]).reshape(-1, 1)
patron_2.T @ M @ patron_2

array([[0]])

El patrón que detecta M es P = 
$\left[\begin{array}{ccc}
1 & 1\\
1 & 0
\end{array}\right]$

In [15]:
b = np.random.randint(0, 4, size=(2, 1))

for k in range(3, 8):
    epsilon = 1 * (10 ** (-k))
    print(epsilon)
    A = np.array([
        [1, 1 + epsilon],
        [1-epsilon, 1]
    ])
    print(np.linalg.solve(A, b))


0.001
[[ 997999.9998605 ]
 [-996999.99986064]]
0.0001
[[ 99979999.49762456]
 [-99969999.4976748 ]]
1e-05
[[ 9.99981027e+09]
 [-9.99971027e+09]]
1e-06
[[ 9.99909107e+11]
 [-9.99908108e+11]]
1e-07
[[ 1.01204466e+14]
 [-1.01204456e+14]]


In [24]:
# Ejercicio 20

A = np.array([
    [4.5, 3.1],
    [1.6, 1.1]
])

b = np.array([19.249, 6.843]).reshape(-1, 1)
b_round = np.array([19.25, 6.84]).reshape(-1, 1)

print(np.linalg.solve(A, b))
print(np.linalg.solve(A, b_round))

print(np.linalg.cond(A))

[[3.94]
 [0.49]]
[[2.9]
 [2. ]]
3362.9997026460996


In [54]:
# Ejercicio 21
A = np.array([
    [4, 0, -7, -7],
    [-6, 1, 11, 9],
    [7, -5, 10, 19],
    [-1, 2, 3, -1]
])
print(np.linalg.cond(A))

x = np.random.randint(-15, 15, size=(4, 1))
b = A @ x
np.linalg.solve(A, b) - x

23682.927874709585


array([[-4.85833596e-13],
       [-1.36690659e-11],
       [ 6.64179822e-12],
       [-6.91358082e-12]])

In [61]:
# Ejercicio 22
A = np.array([
    [5, 3, 1, 7, 9],
    [6, 4, 2, 8, -8],
    [7, 5, 3, 10, 9],
    [9, 6, 4, -9, -5],
    [8, 5, 2, 11, 4]
])

print(np.linalg.cond(A))

x = np.random.randint(-15, 15, size=(5, 1))
b = A @ x
np.linalg.solve(A, b) - x

68622.45483765131


array([[ 7.77848896e-11],
       [-1.65703007e-10],
       [ 8.21067658e-11],
       [ 3.87245791e-12],
       [-1.13686838e-13]])

In [49]:
# Ejercicio 26 
A  = np.random.randint(0, 10, (20, 30))

# a)
A[14:20, :]
A[:, 4:10]
# b)
B = np.random.randint(0, 1, (5, 10))
A[9:14, 19:29] = B
# c)
C = np.concatenate([np.concatenate([A, np.zeros((20, 20))], axis=1), np.concatenate([np.zeros((30, 30)), A.T], axis=1)], axis=0)
print(C)

[[6. 6. 8. ... 0. 0. 0.]
 [4. 1. 7. ... 0. 0. 0.]
 [9. 8. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 3. 0. 1.]
 [0. 0. 0. ... 7. 7. 6.]
 [0. 0. 0. ... 6. 7. 5.]]


In [51]:
# Ejercicio 27
A = np.random.randint(0, 5, (50, 50))
B = np.random.randint(0, 5, (50, 50))

def sumaPorPartes(A, B):
    A11 = A[:25, :25]
    A12 = A[:25, 25:]
    A21 = A[25:, :25]
    A22 = A[25:, 25:]

    B11 = B[:25, :25]
    B12 = B[:25, 25:]
    B21 = B[25:, :25]
    B22 = B[25:, 25:]

    C11 = A11 + B11
    C12 = A12 + B12
    C21 = A21 + B21
    C22 = A22 + B22

    return np.concatenate([np.concatenate([C11, C12], axis=1), np.concatenate([C21, C22], axis=1)], axis=0)

def multiplicacionPorPartes(A, B):
    A11, A12 = A[:25, :25], A[:25, 25:]
    A21, A22 = A[25:, :25], A[25:, 25:]

    B11, B12 = B[:25, :25], B[:25, 25:]
    B21, B22 = B[25:, :25], B[25:, 25:]


    C11 = A11 @ B11 + A12 @ B21
    C12 = A11 @ B12 + A12 @ B22
    C21 = A21 @ B11 + A22 @ B21
    C22 = A21 @ B12 + A22 @ B22

    return np.concatenate([np.concatenate([C11, C12], axis=1), np.concatenate([C21, C22], axis=1)], axis=0)

multiplicacionPorPartes(A, B)

array([[151, 199, 143, ..., 171, 190, 195],
       [180, 257, 169, ..., 235, 229, 201],
       [206, 249, 193, ..., 251, 227, 243],
       ...,
       [197, 265, 153, ..., 229, 248, 224],
       [190, 221, 168, ..., 208, 216, 248],
       [183, 206, 173, ..., 213, 173, 203]])

In [87]:
# Ejercicio 28
def mult(A, B):
    m = [[] for _ in range(len(A))]
    for col in range(len(B[0])):
        for row in range(len(A)):
            c_ij = 0
            for e in range(len(B[0])):
                c_ij += (A[col][e] * B[e][row])
            m[col].append(c_ij)

    return m

def multPartes(A:list, B:list, bloque:int):
    if len(A) % bloque != 0:
        return ValueError('No se puede dividir en esos bloques') 
    
    c_b = len(A) // bloque
    C = []
    for i in range(c_b):
        for j in range(c_b):
            Aij = [row[j*c_b: (j+1)*c_b] for row in A[i*c_b: (i+1)*c_b]]
            Bij = [row[i*c_b: (i+1)*c_b] for row in B[j*c_b: (j+1)*c_b]]
            print(Aij, Bij)
            # Cij = mult(Aij, Bij)  
            # C.append(Cij)

    return C



In [90]:
A = [
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
]

B = [
    [1, 5, 3, 8],
    [5, 6, 8, 2],
    [3, 6, 3 ,9],
    [8, 4, 3, 3]
]

C = [
    [A11*B11 + A12*B21, A11*B12 + A12*B22],
    [A21*B11 + A22*B21, A21*B12 + A22*B22]
]

multPartes(A, B, 2)

[[1, 0], [0, 1]] [[1, 5], [5, 6]]
[[0, 0], [0, 0]] [[3, 6], [8, 4]]
[[0, 0], [0, 0]] [[3, 8], [8, 2]]
[[1, 0], [0, 1]] [[3, 9], [3, 3]]


[]

In [3]:
# Ejercicio 30
CIE = np.array([
    [0.61, 0.29, 0.150],
    [0.32, 0.59, 0.063],
    [0.04, 0.12, 0.787]
])

CIE_INV = np.linalg.inv(CIE)

Sea CIE = 
$\left[\begin{array}{ccc}
0,61 \ \ 0,29  \ \ 0,150 \\
0,32 \ \ 0,59 \ \ 0,063 \\
0,04 \ \ 0,12 \ \ 0,787
\end{array}\right]$

CIE 
$\left[\begin{array}{ccc}
R \\
G \\ 
B
\end{array}\right]$ = 
$\left[\begin{array}{ccc}
X \\
Y \\
Z
\end{array}\right]$ => $CIE^{-1}$
$\left[\begin{array}{ccc}
X \\
Y \\
Z
\end{array}\right]$ = 
$\left[\begin{array}{ccc}
R \\
G \\ 
B
\end{array}\right]$

In [7]:
rgb = np.array([140, 255, 200]).reshape(-1, 1)
xyz = CIE @ rgb
CIE_INV @ xyz

array([[140.],
       [255.],
       [200.]])

In [11]:
# Ejercicio 31
RGB_TO_YIQ = np.array([
    [0.299, 0.587, 0.114],
    [0.596, -0.275, -0.321],
    [0.212, -0.528, 0.311]
])

RGB_TO_YIQ_INV = np.linalg.inv(RGB_TO_YIQ)
RGB_TO_YIQ_INV

def yiq_to_rgb(YIQ:np.array):
    return RGB_TO_YIQ_INV @ YIQ

