In [1]:
import numpy as np
import scipy.linalg as la

In [30]:
A = np.array([
    [3, -1, 0, 0],
    [-1, 3, -1, 0],
    [0, -1, 3, -1],
    [0, 0, -1, 3]
])

t0 = np.array([
    10, 15, 15, 10
]).reshape(-1, 1)

In [31]:
U = np.array([
    [3, -1, 0, 0],
    [0, 8/3, -1, 0],
    [0, 0, 21/8, -1],
    [0, 0, 0, 55/21]
])

L = np.array([
    [1, 0, 0, 0],
    [-1/3, 1, 0, 0],
    [0, -3/8, 1, 0],
    [0, 0, -8/21, 1]
])

In [40]:
y1 = np.linalg.solve(L, t0)
t1 = np.linalg.solve(U, y1)

y2 = np.linalg.solve(L, t1)
t2 = np.linalg.solve(U, y2)

y3 = np.linalg.solve(L, t2)
t3 = np.linalg.solve(U, y3)

y4 = np.linalg.solve(L, t3)
t4 = np.linalg.solve(U, y4)


In [7]:
A = np.array([
    [3, -5, -9],
    [8, 7, -6],
    [-5, -8, 3],
    [2, -2, -9],
])

y = np.array([-4, -8, 6, -5]).reshape(-1, 1)

Ay = np.concatenate((A, y), axis=1) 
Ay

array([[ 3, -5, -9, -4],
       [ 8,  7, -6, -8],
       [-5, -8,  3,  6],
       [ 2, -2, -9, -5]])

In [12]:
# Si Aw = 0, w pertenece a Nul A
A = np.array([
    [3, -5, -3],
    [6, -2, 0],
    [-8,4, 1]
])

w = np.array([1, 3, -4])

A @ w

array([0, 0, 0])

In [19]:
# 18
A = np.array([
    [-8, 5, -2, 0],
    [-5, 2, 1, -2],
    [10, -8, 6, -3],
    [3, -2, 1, 0]
])

w = np.array([1, 2, 1, 0]).reshape(-1, 1)

# w pertenece a Nul A
print(A @ w)

# w pertenece a Col A
print(np.linalg.solve(A, w))

[[0]
 [0]
 [0]
 [0]]
[[ 6.]
 [13.]
 [ 8.]
 [ 1.]]
